### ISSUE TITLE
ベル？

### ISSUE THREAD

**Issue by taisukef** [misakiotb/shop-schedule-fukui-data#2]
<img width="888" alt="image" src="https://github.com/user-attachments/assets/5a70af13-b4e9-465b-8231-e6cf738cc94c" />
ベルの位置にアルプラ武生と記載発見

**Comment by misakiotb** [comment]
アルプラザ、座標を全部コピーしてしまっていました。
修正しますー

**Comment by misakiotb** [comment]
アルプラザの座標修正済みです。
